#!/usr/bin/env python3
"""The user's 20 screenshots, transcribed and de-duplicated by apparatus name.
Artwork is original parametric geometry; no screenshot pixels or NOBOOK assets.
"""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
entries=[]
def add(group, model, action, names, **kw):
    for name in names.split('|'):
        entries.append(dict(id=f'eq{len(entries)+1:03}',name=name,category=group,model=model,action=action,**kw))
add('加热','lamp','heater','酒精灯',source=1)
add('取用','match','ignite','火柴')
add('容器','dropper','vessel','胶头滴管|长胶头滴管',capacity_ml=5)
add('取用','tongs','hold','镊子|坩埚钳')
add('支撑','mesh','support','陶土网|酒精灯罩')
add('支撑','stand','support','带铁夹的铁架台|带铁圈的铁架台|铁架台')
add('支撑','clamp','support','铁夹侧视|铁夹|滴定管夹|试管夹')
add('取用','spoon','scoop','药匙|燃烧匙|带孔燃烧匙')
add('连接','tube90','connect','九十度玻璃导管|九十度导管（不可拆分）|九十度玻璃管',ports=2)
add('连接','bent','connect','可弯曲导管|六十度弯管|尖嘴金属管|弯嘴金属管|牛角管',ports=2)
add('连接','tube','connect','直导管|针头',ports=2)
add('连接','hose','connect','橡胶管',ports=2)
add('连接','valve','valve','止水夹',ports=2)
add('连接','stopper','seal','橡胶塞')
add('连接','stoppertube','connect','橡胶塞（带导管）',ports=2)
add('取用','rod','stir','玻璃棒|环形玻璃搅拌棒')
add('支撑','triangle','support','泥三角')
add('取用','scissors','cut','剪刀|小刀')
add('支撑','sheet','cover','玻璃片|木盖|塑料隔板')
add('取用','brush','clean','试管刷')
add('测量','thermometer','temperature','温度计|高温温度计')
add('测量','timer','timer','秒表')
add('连接','tee','connect','T形玻璃导管',ports=3)
add('连接','wye','connect','Y形玻璃导管',ports=3)
add('耗材','wire','material','镁条|铂丝|铜丝|铁丝|带木条的铁丝')
add('取用','sheet','polish','砂纸')
add('测量','paper','ph','pH试纸|红色石蕊试纸|蓝色石蕊试纸|酚酞试纸')
add('测量','paper','iodine','淀粉碘化钾试纸')
add('组合装置','condenserstand','condenser','直形冷凝管装置|球形冷凝管装置',ports=4)
add('连接','condenser','condenser','球形冷凝管',ports=4)
add('测量','balance','weigh','电子天平|天平和砝码')
add('取用','sheet','weigh','称量纸')
add('支撑','ring','support','铁圈')
add('支撑','block','support','木块')
add('支撑','rack','support','试管架')
add('支撑','tripod','support','三脚架')
add('支撑','stairs','support','阶梯铁片')
add('支撑','lift','lift','升降台')
add('耗材','sheet','material','黄铜片')
add('组合装置','electrolyzer','electrolysis','霍夫曼电解器')
add('加热','mantle','heater','电热套',source=0)
add('加热','bath','bath','冰水浴|水浴锅')
add('容器','tank','vessel','水槽',capacity_ml=1000)
add('取用','sheet','scoop','纸槽')
add('容器','syringe','vessel','塑料注射器',capacity_ml=10)
add('容器','syringe','vessel','大塑料注射器',capacity_ml=100)
add('容器','syringe','vessel','塑料注射器50ml',capacity_ml=50)
add('组合装置','doublebulb','no2','二氧化氮平衡球')
add('容器','balloon','gas','气球')
add('测量','paperflower','ph','石蕊纸花')
add('取用','paper','filter','定性滤纸')
add('连接','dryingtube','dry','球形干燥管|碱石灰干燥管|五氧化二磷干燥管',ports=2)
add('加热','bunsen','heater','本生灯',source=2)
add('耗材','cotton','material','棉花|热毛巾|布条|馒头|小木条|抽纸盒')
add('测量','lens','optics','放大镜|蓝色钴玻璃|激光笔')
add('加热','candle','material','蜡烛')
add('耗材','firework','material','烟花')
add('测量','meter','ph','pH计')
add('加热','torch','heater','酒精喷灯',source=5)
add('容器','spray','material','酒精喷壶')
add('容器','syringe','no2','充有二氧化氮的50ml注射器',capacity_ml=50)
add('组合装置','washbottle','dry','酸性气体干燥装置|碱性气体干燥装置',ports=2)
add('组合装置','gasjar','gas','向下排空气法|向上排空气法',ports=1)
add('组合装置','collection','gas','排水集气法',ports=1)
add('组合装置','conductivity','conductivity','电导率测定装置|溶液导电性')
add('组合装置','washbottle','scrub','尾气处理装置|洗气装置',ports=2)
add('组合装置','generator','gasreaction','固液加热制气装置|固固加热制气装置|固液不加热制气装置',ports=1)
add('容器','washbottle','vessel','多功能瓶',capacity_ml=250,ports=3)
add('测量','spectrum','spectrum','氢原子能级|光谱管组')
# The six additional container screenshots.
add('容器','flask','vessel','圆底烧瓶|平底烧瓶',capacity_ml=250)
add('容器','separatory','vessel','球形分液漏斗|梨形分液漏斗|平衡气压的球形分液漏斗|直形分液漏斗|滴液漏斗|恒压滴液漏斗',capacity_ml=100,ports=2)
add('容器','gasjar','vessel','集气瓶|五等分集气瓶',capacity_ml=250)
add('容器','testtube','vessel','小试管',capacity_ml=10)
add('容器','testtube','vessel','大试管|具支试管',capacity_ml=50)
for cap in [100,250,1000]: add('容器','beaker','vessel',f'烧杯{cap}mL',capacity_ml=cap)
add('容器','flask3','vessel','三颈烧瓶',capacity_ml=250,ports=3)
add('容器','funnel','vessel','长颈漏斗|小号三角漏斗|三角漏斗',capacity_ml=50,ports=2)
add('容器','washbottle','vessel','洗瓶250mL',capacity_ml=250)
add('容器','flaskside','vessel','蒸馏烧瓶',capacity_ml=250,ports=2)
add('容器','bottle','vessel','细口瓶|广口瓶',capacity_ml=250)
add('组合装置','kipp','gasreaction','启普发生器',ports=2)
add('容器','utube','vessel','具支U型管|U型管|测定气体体积U型管',capacity_ml=50,ports=2)
add('容器','utube','material','硫酸铜U型管|碱石灰U型管',ports=2)
add('容器','crucible','vessel','坩埚',capacity_ml=50)
add('容器','dish','vessel','小蒸发皿',capacity_ml=50)
add('容器','dish','vessel','大蒸发皿|表面皿',capacity_ml=100)
add('容器','spotplate','vessel','点滴板',capacity_ml=5)
add('取用','mortar','grind','研钵和研杵棒')
for cap in [10,50,100]: add('容器','cylinder','vessel',f'量筒{cap}mL',capacity_ml=cap)
add('容器','volumetric','vessel','容量瓶250mL',capacity_ml=250)
add('容器','hardtube','vessel','硬质玻璃管',capacity_ml=50,ports=2)
add('容器','hardtube','vessel','大硬质玻璃管',capacity_ml=100,ports=2)
add('容器','burette','vessel','酸式滴定管|碱式滴定管',capacity_ml=50,ports=2)
add('容器','bottle','material','浓硫酸干燥瓶|二氧化碳瓶|消毒液|洁厕灵',capacity_ml=250)
add('容器','insulated','vessel','保温烧杯',capacity_ml=250)
add('组合装置','calorimeter','calorimeter','保温烧杯组合')
add('容器','waste','vessel','废液缸|污物杯',capacity_ml=1000)
# Earlier explicitly requested sources and current useful laboratory basics.
add('加热','torch','heater','氢氧焰',source=3)
add('加热','torch','heater','乙炔氧焰',source=4)
add('加热','hotplate','heater','电热板',source=0)
add('取用','stirrer','stir','电动搅拌器')
assert len({e['name'] for e in entries})==len(entries)
for e in entries:
    e['capabilities']=['place','select','move','rotate','remove']
    if e.get('ports',0): e['capabilities'].append('connect')
    e['origin']='用户器材参考；原创参数化模型'
data=dict(schema=1,items=entries)
for file in [ROOT/'data/apparatus.json', ROOT/'godot/data/apparatus.json']:
    file.write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n')
print(f'{len(entries)} distinct apparatus entries')
