#!/usr/bin/env python3
"""Project-local Cantera 3.2.0 is an independent reference, not a runtime dependency."""
import cantera as ct
import json, hashlib, math
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
assert ct.__version__=='3.2.0'
names=['CO2','H2O','CO','H2','O2','N2','H','O','OH','NO','N','HO2','H2O2','CH4','C2H2,acetylene','C2H5OH']
all_species={s.name:s for s in ct.Species.list_from_file('nasa_gas.yaml')}
species=[all_species[n] for n in names]
rows=[]
for s in species:
    c=s.thermo.coeffs
    rows.append(dict(name=s.name,atoms=[s.composition.get(e,0) for e in ['C','H','O','N']],mid=c[0],high=c[1:8].tolist(),low=c[8:15].tolist(),note=dict(s.input_data['thermo']).get('note','')))
root={'source':'Cantera v3.2.0 data/nasa_gas.yaml; NASA TM-4513 (1993)','reference_pressure_pa':101325,'species':rows}
(ROOT/'data/combustion-thermo.json').write_text(json.dumps(root,indent=2)+'\n')
out='// Generated by scripts/generate_combustion_data.py; Cantera BSD-3-Clause / NASA TM-4513.\n'
out+='static const std::array<ThermoSpecies,16> species = {{\n'
for s in rows:
    arr=lambda xs:'{'+','.join(format(x,'.17g') for x in xs)+'}'
    out+='  {"'+s['name']+'",'+arr(s['atoms'])+','+str(s['mid'])+','+arr(s['low'])+','+arr(s['high'])+'},\n'
out+='}};\n'
(ROOT/'src/science/combustion_data.inc').write_text(out)
refs=[]
for fuel,oxygen in [('C2H5OH',False),('CH4',False),('H2',True),('C2H2,acetylene',True),('C2H5OH',False)]:
    for excess in [1,1.2,1.5,2]:
        gas=ct.Solution(thermo='ideal-gas',species=species)
        a=all_species[fuel].composition
        o=a.get('C',0)+a.get('H',0)/4-a.get('O',0)/2
        X={fuel:1,'O2':o*excess}
        if not oxygen: X['N2']=o*excess*3.76
        gas.TPX=298.15,ct.one_atm,X
        initial_h=gas.enthalpy_mass
        mass=gas.mean_molecular_weight*sum(X.values())/1000
        if fuel=='C2H5OH':
            tr=298.15/513.9
            vaporization=50430*math.exp(0.4475*tr)*(1-tr)**0.4989
            initial_h-=vaporization/mass
            gas.HP=initial_h,ct.one_atm
        gas.equilibrate('HP',solver='auto',rtol=1e-9,max_steps=2000)
        total_mol=mass/(gas.mean_molecular_weight/1000)
        refs.append(dict(source=len(refs)//4+1,excess=excess,temperature_k=gas.T,products={n:float(x*total_mol) for n,x in zip(names,gas.X)},enthalpy_j=initial_h*mass))
(ROOT/'data/combustion-reference.json').write_text(json.dumps(refs,indent=2)+'\n')
print('Generated 16 species and',len(refs),'HP references')
